# ---------------------------------------------------------
# Do not modify this file. It was generated by `scripts/generate_typed_dicts.py`.
# ---------------------------------------------------------


from ._client import ChatClientArgs

__all__ = ("ChatClientArgs",)
