# ---------------------------------------------------------
# Do not modify this file. It was generated by `scripts/generate_typed_dicts.py`.
# ---------------------------------------------------------


from typing import Awaitable, Callable, Mapping, Optional, TypedDict, Union

import httpx
import openai
import openai.auth._workload


class ChatClientArgs(TypedDict, total=False):
    api_key: Union[str, Callable[[], Awaitable[str]], None]
    admin_api_key: str | None
    workload_identity: openai.auth._workload.WorkloadIdentity | None
    organization: str | None
    project: str | None
    webhook_secret: str | None
    base_url: str | httpx.URL | None
    websocket_base_url: str | httpx.URL | None
    timeout: float | openai.Timeout | None | openai.NotGiven
    max_retries: int
    default_headers: Optional[Mapping[str, str]]
    default_query: Optional[Mapping[str, object]]
    http_client: httpx.AsyncClient | None
    _strict_response_validation: bool
    _enforce_credentials: bool
