# ---------------------------------------------------------
# Do not modify this file. It was generated by `scripts/generate_typed_dicts.py`.
# ---------------------------------------------------------


from typing import Iterable, Literal, Mapping, Optional, Sequence, TypedDict, Union

import openai
import openai.types.chat.chat_completion_allowed_tool_choice_param
import openai.types.chat.chat_completion_assistant_message_param
import openai.types.chat.chat_completion_audio_param
import openai.types.chat.chat_completion_custom_tool_param
import openai.types.chat.chat_completion_developer_message_param
import openai.types.chat.chat_completion_function_call_option_param
import openai.types.chat.chat_completion_function_message_param
import openai.types.chat.chat_completion_function_tool_param
import openai.types.chat.chat_completion_named_tool_choice_custom_param
import openai.types.chat.chat_completion_named_tool_choice_param
import openai.types.chat.chat_completion_prediction_content_param
import openai.types.chat.chat_completion_stream_options_param
import openai.types.chat.chat_completion_system_message_param
import openai.types.chat.chat_completion_tool_message_param
import openai.types.chat.chat_completion_user_message_param
import openai.types.chat.completion_create_params
import openai.types.shared_params.response_format_json_object
import openai.types.shared_params.response_format_json_schema
import openai.types.shared_params.response_format_text


class SubmitInputArgs(TypedDict, total=False):
    messages: Iterable[
        Union[
            openai.types.chat.chat_completion_developer_message_param.ChatCompletionDeveloperMessageParam,
            openai.types.chat.chat_completion_system_message_param.ChatCompletionSystemMessageParam,
            openai.types.chat.chat_completion_user_message_param.ChatCompletionUserMessageParam,
            openai.types.chat.chat_completion_assistant_message_param.ChatCompletionAssistantMessageParam,
            openai.types.chat.chat_completion_tool_message_param.ChatCompletionToolMessageParam,
            openai.types.chat.chat_completion_function_message_param.ChatCompletionFunctionMessageParam,
        ]
    ]
    model: Union[
        str,
        Literal[
            "gpt-5",
            "gpt-5-mini",
            "gpt-5-nano",
            "gpt-5-2025-08-07",
            "gpt-5-mini-2025-08-07",
            "gpt-5-nano-2025-08-07",
            "gpt-5-chat-latest",
            "gpt-4.1",
            "gpt-4.1-mini",
            "gpt-4.1-nano",
            "gpt-4.1-2025-04-14",
            "gpt-4.1-mini-2025-04-14",
            "gpt-4.1-nano-2025-04-14",
            "o4-mini",
            "o4-mini-2025-04-16",
            "o3",
            "o3-2025-04-16",
            "o3-mini",
            "o3-mini-2025-01-31",
            "o1",
            "o1-2024-12-17",
            "o1-preview",
            "o1-preview-2024-09-12",
            "o1-mini",
            "o1-mini-2024-09-12",
            "gpt-4o",
            "gpt-4o-2024-11-20",
            "gpt-4o-2024-08-06",
            "gpt-4o-2024-05-13",
            "gpt-4o-audio-preview",
            "gpt-4o-audio-preview-2024-10-01",
            "gpt-4o-audio-preview-2024-12-17",
            "gpt-4o-audio-preview-2025-06-03",
            "gpt-4o-mini-audio-preview",
            "gpt-4o-mini-audio-preview-2024-12-17",
            "gpt-4o-search-preview",
            "gpt-4o-mini-search-preview",
            "gpt-4o-search-preview-2025-03-11",
            "gpt-4o-mini-search-preview-2025-03-11",
            "chatgpt-4o-latest",
            "codex-mini-latest",
            "gpt-4o-mini",
            "gpt-4o-mini-2024-07-18",
            "gpt-4-turbo",
            "gpt-4-turbo-2024-04-09",
            "gpt-4-0125-preview",
            "gpt-4-turbo-preview",
            "gpt-4-1106-preview",
            "gpt-4-vision-preview",
            "gpt-4",
            "gpt-4-0314",
            "gpt-4-0613",
            "gpt-4-32k",
            "gpt-4-32k-0314",
            "gpt-4-32k-0613",
            "gpt-3.5-turbo",
            "gpt-3.5-turbo-16k",
            "gpt-3.5-turbo-0301",
            "gpt-3.5-turbo-0613",
            "gpt-3.5-turbo-1106",
            "gpt-3.5-turbo-0125",
            "gpt-3.5-turbo-16k-0613",
        ],
    ]
    audio: Union[
        openai.types.chat.chat_completion_audio_param.ChatCompletionAudioParam,
        None,
        openai.Omit,
    ]
    frequency_penalty: Union[float, None, openai.Omit]
    function_call: Union[
        Literal["none", "auto"],
        openai.types.chat.chat_completion_function_call_option_param.ChatCompletionFunctionCallOptionParam,
        openai.Omit,
    ]
    functions: Union[
        Iterable[openai.types.chat.completion_create_params.Function], openai.Omit
    ]
    logit_bias: Union[dict[str, int], None, openai.Omit]
    logprobs: Union[bool, None, openai.Omit]
    max_completion_tokens: Union[int, None, openai.Omit]
    max_tokens: Union[int, None, openai.Omit]
    metadata: Union[dict[str, str], None, openai.Omit]
    modalities: Union[list[Literal["text", "audio"]], None, openai.Omit]
    n: Union[int, None, openai.Omit]
    parallel_tool_calls: bool | openai.Omit
    prediction: Union[
        openai.types.chat.chat_completion_prediction_content_param.ChatCompletionPredictionContentParam,
        None,
        openai.Omit,
    ]
    presence_penalty: Union[float, None, openai.Omit]
    prompt_cache_key: str | openai.Omit
    reasoning_effort: Union[
        Literal["minimal", "low", "medium", "high"], None, openai.Omit
    ]
    response_format: Union[
        openai.types.shared_params.response_format_text.ResponseFormatText,
        openai.types.shared_params.response_format_json_schema.ResponseFormatJSONSchema,
        openai.types.shared_params.response_format_json_object.ResponseFormatJSONObject,
        openai.Omit,
    ]
    safety_identifier: str | openai.Omit
    seed: Union[int, None, openai.Omit]
    service_tier: Union[
        Literal["auto", "default", "flex", "scale", "priority"], None, openai.Omit
    ]
    stop: Union[str, None, Sequence[str], openai.Omit]
    store: Union[bool, None, openai.Omit]
    stream: Union[Literal[False], None, Literal[True], openai.Omit]
    stream_options: Union[
        openai.types.chat.chat_completion_stream_options_param.ChatCompletionStreamOptionsParam,
        None,
        openai.Omit,
    ]
    temperature: Union[float, None, openai.Omit]
    tool_choice: Union[
        Literal["none", "auto", "required"],
        openai.types.chat.chat_completion_allowed_tool_choice_param.ChatCompletionAllowedToolChoiceParam,
        openai.types.chat.chat_completion_named_tool_choice_param.ChatCompletionNamedToolChoiceParam,
        openai.types.chat.chat_completion_named_tool_choice_custom_param.ChatCompletionNamedToolChoiceCustomParam,
        openai.Omit,
    ]
    tools: Union[
        Iterable[
            Union[
                openai.types.chat.chat_completion_function_tool_param.ChatCompletionFunctionToolParam,
                openai.types.chat.chat_completion_custom_tool_param.ChatCompletionCustomToolParam,
            ]
        ],
        openai.Omit,
    ]
    top_logprobs: Union[int, None, openai.Omit]
    top_p: Union[float, None, openai.Omit]
    user: str | openai.Omit
    verbosity: Union[Literal["low", "medium", "high"], None, openai.Omit]
    web_search_options: (
        openai.types.chat.completion_create_params.WebSearchOptions | openai.Omit
    )
    extra_headers: Optional[Mapping[str, Union[str, openai.Omit]]]
    extra_query: Optional[Mapping[str, object]]
    extra_body: object | None
    timeout: float | openai.Timeout | None | openai.NotGiven


from typing import Iterable, Literal, Mapping, Optional, TypedDict, Union

import openai
import openai.types.responses.computer_tool_param
import openai.types.responses.custom_tool_param
import openai.types.responses.easy_input_message_param
import openai.types.responses.file_search_tool_param
import openai.types.responses.function_tool_param
import openai.types.responses.response_code_interpreter_tool_call_param
import openai.types.responses.response_computer_tool_call_param
import openai.types.responses.response_conversation_param
import openai.types.responses.response_create_params
import openai.types.responses.response_custom_tool_call_output_param
import openai.types.responses.response_custom_tool_call_param
import openai.types.responses.response_file_search_tool_call_param
import openai.types.responses.response_function_tool_call_param
import openai.types.responses.response_function_web_search_param
import openai.types.responses.response_input_param
import openai.types.responses.response_output_message_param
import openai.types.responses.response_prompt_param
import openai.types.responses.response_reasoning_item_param
import openai.types.responses.response_text_config_param
import openai.types.responses.tool_choice_allowed_param
import openai.types.responses.tool_choice_custom_param
import openai.types.responses.tool_choice_function_param
import openai.types.responses.tool_choice_mcp_param
import openai.types.responses.tool_choice_types_param
import openai.types.responses.tool_param
import openai.types.responses.web_search_preview_tool_param
import openai.types.responses.web_search_tool_param
import openai.types.shared_params.reasoning


class ResponsesSubmitInputArgs(TypedDict, total=False):
    background: Union[bool, None, openai.Omit]
    conversation: Union[
        str,
        openai.types.responses.response_conversation_param.ResponseConversationParam,
        None,
        openai.Omit,
    ]
    include: Union[
        list[
            Literal[
                "file_search_call.results",
                "web_search_call.results",
                "web_search_call.action.sources",
                "message.input_image.image_url",
                "computer_call_output.output.image_url",
                "code_interpreter_call.outputs",
                "reasoning.encrypted_content",
                "message.output_text.logprobs",
            ]
        ],
        None,
        openai.Omit,
    ]
    input: Union[
        str,
        list[
            Union[
                openai.types.responses.easy_input_message_param.EasyInputMessageParam,
                openai.types.responses.response_input_param.Message,
                openai.types.responses.response_output_message_param.ResponseOutputMessageParam,
                openai.types.responses.response_file_search_tool_call_param.ResponseFileSearchToolCallParam,
                openai.types.responses.response_computer_tool_call_param.ResponseComputerToolCallParam,
                openai.types.responses.response_input_param.ComputerCallOutput,
                openai.types.responses.response_function_web_search_param.ResponseFunctionWebSearchParam,
                openai.types.responses.response_function_tool_call_param.ResponseFunctionToolCallParam,
                openai.types.responses.response_input_param.FunctionCallOutput,
                openai.types.responses.response_reasoning_item_param.ResponseReasoningItemParam,
                openai.types.responses.response_input_param.ImageGenerationCall,
                openai.types.responses.response_code_interpreter_tool_call_param.ResponseCodeInterpreterToolCallParam,
                openai.types.responses.response_input_param.LocalShellCall,
                openai.types.responses.response_input_param.LocalShellCallOutput,
                openai.types.responses.response_input_param.McpListTools,
                openai.types.responses.response_input_param.McpApprovalRequest,
                openai.types.responses.response_input_param.McpApprovalResponse,
                openai.types.responses.response_input_param.McpCall,
                openai.types.responses.response_custom_tool_call_output_param.ResponseCustomToolCallOutputParam,
                openai.types.responses.response_custom_tool_call_param.ResponseCustomToolCallParam,
                openai.types.responses.response_input_param.ItemReference,
            ]
        ],
        openai.Omit,
    ]
    instructions: Union[str, None, openai.Omit]
    max_output_tokens: Union[int, None, openai.Omit]
    max_tool_calls: Union[int, None, openai.Omit]
    metadata: Union[dict[str, str], None, openai.Omit]
    model: Union[
        str,
        Literal[
            "gpt-5",
            "gpt-5-mini",
            "gpt-5-nano",
            "gpt-5-2025-08-07",
            "gpt-5-mini-2025-08-07",
            "gpt-5-nano-2025-08-07",
            "gpt-5-chat-latest",
            "gpt-4.1",
            "gpt-4.1-mini",
            "gpt-4.1-nano",
            "gpt-4.1-2025-04-14",
            "gpt-4.1-mini-2025-04-14",
            "gpt-4.1-nano-2025-04-14",
            "o4-mini",
            "o4-mini-2025-04-16",
            "o3",
            "o3-2025-04-16",
            "o3-mini",
            "o3-mini-2025-01-31",
            "o1",
            "o1-2024-12-17",
            "o1-preview",
            "o1-preview-2024-09-12",
            "o1-mini",
            "o1-mini-2024-09-12",
            "gpt-4o",
            "gpt-4o-2024-11-20",
            "gpt-4o-2024-08-06",
            "gpt-4o-2024-05-13",
            "gpt-4o-audio-preview",
            "gpt-4o-audio-preview-2024-10-01",
            "gpt-4o-audio-preview-2024-12-17",
            "gpt-4o-audio-preview-2025-06-03",
            "gpt-4o-mini-audio-preview",
            "gpt-4o-mini-audio-preview-2024-12-17",
            "gpt-4o-search-preview",
            "gpt-4o-mini-search-preview",
            "gpt-4o-search-preview-2025-03-11",
            "gpt-4o-mini-search-preview-2025-03-11",
            "chatgpt-4o-latest",
            "codex-mini-latest",
            "gpt-4o-mini",
            "gpt-4o-mini-2024-07-18",
            "gpt-4-turbo",
            "gpt-4-turbo-2024-04-09",
            "gpt-4-0125-preview",
            "gpt-4-turbo-preview",
            "gpt-4-1106-preview",
            "gpt-4-vision-preview",
            "gpt-4",
            "gpt-4-0314",
            "gpt-4-0613",
            "gpt-4-32k",
            "gpt-4-32k-0314",
            "gpt-4-32k-0613",
            "gpt-3.5-turbo",
            "gpt-3.5-turbo-16k",
            "gpt-3.5-turbo-0301",
            "gpt-3.5-turbo-0613",
            "gpt-3.5-turbo-1106",
            "gpt-3.5-turbo-0125",
            "gpt-3.5-turbo-16k-0613",
        ],
        Literal[
            "o1-pro",
            "o1-pro-2025-03-19",
            "o3-pro",
            "o3-pro-2025-06-10",
            "o3-deep-research",
            "o3-deep-research-2025-06-26",
            "o4-mini-deep-research",
            "o4-mini-deep-research-2025-06-26",
            "computer-use-preview",
            "computer-use-preview-2025-03-11",
            "gpt-5-codex",
            "gpt-5-pro",
            "gpt-5-pro-2025-10-06",
        ],
        openai.Omit,
    ]
    parallel_tool_calls: Union[bool, None, openai.Omit]
    previous_response_id: Union[str, None, openai.Omit]
    prompt: Union[
        openai.types.responses.response_prompt_param.ResponsePromptParam,
        None,
        openai.Omit,
    ]
    prompt_cache_key: str | openai.Omit
    reasoning: Union[openai.types.shared_params.reasoning.Reasoning, None, openai.Omit]
    safety_identifier: str | openai.Omit
    service_tier: Union[
        Literal["auto", "default", "flex", "scale", "priority"], None, openai.Omit
    ]
    store: Union[bool, None, openai.Omit]
    stream: Union[Literal[False], None, Literal[True], openai.Omit]
    stream_options: Union[
        openai.types.responses.response_create_params.StreamOptions, None, openai.Omit
    ]
    temperature: Union[float, None, openai.Omit]
    text: (
        openai.types.responses.response_text_config_param.ResponseTextConfigParam
        | openai.Omit
    )
    tool_choice: Union[
        Literal["none", "auto", "required"],
        openai.types.responses.tool_choice_allowed_param.ToolChoiceAllowedParam,
        openai.types.responses.tool_choice_types_param.ToolChoiceTypesParam,
        openai.types.responses.tool_choice_function_param.ToolChoiceFunctionParam,
        openai.types.responses.tool_choice_mcp_param.ToolChoiceMcpParam,
        openai.types.responses.tool_choice_custom_param.ToolChoiceCustomParam,
        openai.Omit,
    ]
    tools: Union[
        Iterable[
            Union[
                openai.types.responses.function_tool_param.FunctionToolParam,
                openai.types.responses.file_search_tool_param.FileSearchToolParam,
                openai.types.responses.computer_tool_param.ComputerToolParam,
                openai.types.responses.web_search_tool_param.WebSearchToolParam,
                openai.types.responses.tool_param.Mcp,
                openai.types.responses.tool_param.CodeInterpreter,
                openai.types.responses.tool_param.ImageGeneration,
                openai.types.responses.tool_param.LocalShell,
                openai.types.responses.custom_tool_param.CustomToolParam,
                openai.types.responses.web_search_preview_tool_param.WebSearchPreviewToolParam,
            ]
        ],
        openai.Omit,
    ]
    top_logprobs: Union[int, None, openai.Omit]
    top_p: Union[float, None, openai.Omit]
    truncation: Union[Literal["auto", "disabled"], None, openai.Omit]
    user: str | openai.Omit
    extra_headers: Optional[Mapping[str, Union[str, openai.Omit]]]
    extra_query: Optional[Mapping[str, object]]
    extra_body: object | None
    timeout: float | openai.Timeout | None | openai.NotGiven
