# ---------------------------------------------------------
# Do not modify this file. It was generated by `scripts/generate_typed_dicts.py`.
# ---------------------------------------------------------

from typing import Literal, Optional, Sequence, TypedDict, Union

import ollama._types


class ChatCompletion(TypedDict, total=False):
    model: str
    tools: Optional[Sequence[ollama._types.Tool]]
    format: Literal["", "json"]
    options: Optional[ollama._types.Options]
    keep_alive: Union[float, str, None]


class ChatCompletionStream(TypedDict, total=False):
    model: str
    tools: Optional[Sequence[ollama._types.Tool]]
    format: Literal["", "json"]
    options: Optional[ollama._types.Options]
    keep_alive: Union[float, str, None]
