# ChatPerplexity { #chatlas.ChatPerplexity }

```python
ChatPerplexity(
    system_prompt=None
    turns=None
    model=None
    api_key=None
    base_url='https://api.perplexity.ai/'
    seed=MISSING
    kwargs=None
)
```

Chat with a model hosted on perplexity.ai

Sign up at <https://www.perplexity.ai>.

This function is a lightweight wrapper around `ChatOpenAI` with
the defaults tweaked for perplexity.ai.

## Parameters {.doc-section .doc-section-parameters}

| Name          | Type                                                                                           | Description                                                                                                                                                                                                                                                                                                                                                                                                                 | Default                        |
|---------------|------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------|
| system_prompt | [Optional](`typing.Optional`)\[[str](`str`)\]                                                  | A system prompt to set the behavior of the assistant.                                                                                                                                                                                                                                                                                                                                                                       | `None`                         |
| turns         | [Optional](`typing.Optional`)\[[list](`list`)\[[Turn](`chatlas._turn.Turn`)\]\]                | A list of turns to start the chat with (i.e., continuing a previous conversation). If not provided, the conversation begins from scratch. Do not provide non-`None` values for both `turns` and `system_prompt`. Each message in the list should be a dictionary with at least `role` (usually `system`, `user`, or `assistant`, but `tool` is also possible). Normally there is also a `content` field, which is a string. | `None`                         |
| model         | [Optional](`typing.Optional`)\[[str](`str`)\]                                                  | The model to use for the chat. The default, None, will pick a reasonable default, and warn you about it. We strongly recommend explicitly choosing a model for all but the most casual use.                                                                                                                                                                                                                                 | `None`                         |
| api_key       | [Optional](`typing.Optional`)\[[str](`str`)\]                                                  | The API key to use for authentication. You generally should not supply this directly, but instead set the `PERPLEXITY_API_KEY` environment variable.                                                                                                                                                                                                                                                                        | `None`                         |
| base_url      | [str](`str`)                                                                                   | The base URL to the endpoint; the default uses Perplexity's API.                                                                                                                                                                                                                                                                                                                                                            | `'https://api.perplexity.ai/'` |
| seed          | [Optional](`typing.Optional`)\[[int](`int`)\] \| [MISSING_TYPE](`chatlas._utils.MISSING_TYPE`) | Optional integer seed that ChatGPT uses to try and make output more reproducible.                                                                                                                                                                                                                                                                                                                                           | `MISSING`                      |
| kwargs        | [Optional](`typing.Optional`)\[\'ProviderClientArgs\'\]                                        | Additional arguments to pass to the `openai.OpenAI()` client constructor.                                                                                                                                                                                                                                                                                                                                                   | `None`                         |

## Returns {.doc-section .doc-section-returns}

| Name   | Type                         | Description                                               |
|--------|------------------------------|-----------------------------------------------------------|
|        | [Chat](`chatlas._chat.Chat`) | A chat object that retains the state of the conversation. |

## Examples {.doc-section .doc-section-examples}

```python
>>> from chatlas import ChatPerplexity
>>> chat = ChatPerplexity()
>>> chat.chat("What is the capital of France?")
```