# Function reference {.doc .doc-index}

## Chat model providers

Start a chat with a particular large language model (llm) provider.

| | |
| --- | --- |
| [ChatAnthropic](ChatAnthropic.qmd#chatlas.ChatAnthropic) | Chat with an Anthropic Claude model. |
| [ChatAzureOpenAI](ChatAzureOpenAI.qmd#chatlas.ChatAzureOpenAI) | Chat with a model hosted on Azure OpenAI. |
| [ChatBedrockAnthropic](ChatBedrockAnthropic.qmd#chatlas.ChatBedrockAnthropic) | Chat with an AWS bedrock model. |
| [ChatGithub](ChatGithub.qmd#chatlas.ChatGithub) | Chat with a model hosted on the GitHub model marketplace. |
| [ChatGoogle](ChatGoogle.qmd#chatlas.ChatGoogle) | Chat with a Google Gemini model. |
| [ChatGroq](ChatGroq.qmd#chatlas.ChatGroq) | Chat with a model hosted on Groq. |
| [ChatOllama](ChatOllama.qmd#chatlas.ChatOllama) | Chat with a local Ollama model. |
| [ChatOpenAI](ChatOpenAI.qmd#chatlas.ChatOpenAI) | Chat with an OpenAI model. |
| [ChatPerplexity](ChatPerplexity.qmd#chatlas.ChatPerplexity) | Chat with a model hosted on perplexity.ai. |

## The chat object

Methods and attributes available on a chat instance

| | |
| --- | --- |
| [Chat](Chat.qmd#chatlas.Chat) | A chat object that can be used to interact with a language model. |

## Image input

Submit image input to the chat

| | |
| --- | --- |
| [image_file](image_file.qmd#chatlas.image_file) | Encode image content from a file for chat input. |
| [image_plot](image_plot.qmd#chatlas.image_plot) | Encode the current matplotlib plot as an image for chat input. |
| [image_url](image_url.qmd#chatlas.image_url) | Encode image content from a URL for chat input. |

## Tool calling

Add context to python function before registering it as a tool.

| | |
| --- | --- |
| [Tool](Tool.qmd#chatlas.Tool) |  |

## Turns

A provider-agnostic representation of content generated during an assistant/user turn.

| | |
| --- | --- |
| [Turn](Turn.qmd#chatlas.Turn) |  |

## Query token usage

| | |
| --- | --- |
| [token_usage](token_usage.qmd#chatlas.token_usage) | Report on token usage in the current session |

## Implement a model provider

| | |
| --- | --- |
| [Provider](Provider.qmd#chatlas.Provider) |  |

## User-facing types

| | |
| --- | --- |
| [types](types.qmd#chatlas.types) |  |