name: Update Pricing

on:
    workflow_dispatch:
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]

jobs:
    check-pricing:
        name: Check for pricing updates in Ellmer
        runs-on: ubuntu-latest

        steps:

            - name: Check for differences
              run: |
                echo "Checking diff between prices.json"
                git diff --no-index https://github.com/posit-dev/chatlas/blob/feature/get_cost/chatlas/data/prices.json https://github.com/tidyverse/ellmer/blob/main/data-raw/prices.json




                
            
        
            